name: Stockify
favicon: null
layout_spectrum: 0.75488
typography_spectrum: 0.6406
title: Inventory Management Made Simple
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#596467'
    - '#b7c3cc'
    - '#f97a76'
  brandStrength: 0.4375
  lightness: 0.75
  saturation: 0.25
  rhythmicContrast: 0.75
purpose: []
